#!/usr/bin/env bash
set -euo pipefail

# ── pco-autoclaw Setup ───────────────────────────────────────────────
# Interactive onboarding script for new churches.
# Creates config.env from your answers. Safe to re-run.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/config.env"
CHURCH_YAML="$SCRIPT_DIR/church.yaml"

echo "╔══════════════════════════════════════════════════════╗"
echo "║          pco-autoclaw — Church Operations            ║"
echo "║          Volunteer Scheduling · Booklets ·           ║"
echo "║          Graphics · Transcription                    ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""

if [[ -f "$CONFIG_FILE" ]]; then
  echo "Found existing config.env — this will update it."
  echo "Press Ctrl+C to cancel, or Enter to continue."
  read -r
fi

# ── Helper ────────────────────────────────────────────────────────────
ask() {
  local prompt="$1"
  local default="${2:-}"
  local var_name="$3"
  if [[ -n "$default" ]]; then
    prompt="$prompt [$default]"
  fi
  printf "%s: " "$prompt"
  read -r value
  value="${value:-$default}"
  eval "$var_name=\"\$value\""
}

ask_secret() {
  local prompt="$1"
  local var_name="$2"
  printf "%s: " "$prompt"
  read -rs value
  echo ""
  eval "$var_name=\"\$value\""
}

section() {
  echo ""
  echo "── $1 ──────────────────────────────────────────────"
  echo ""
}

# ── Church Identity ───────────────────────────────────────────────────
section "Church Identity"

ask "Church name (displayed on graphics)" "" CHURCH_NAME
ask "Path to church logo (white on transparent PNG)" "logo_white.png" CHURCH_LOGO_PATH

# ── Planning Center ───────────────────────────────────────────────────
section "Planning Center"
echo "Get a Personal Access Token at:"
echo "  https://api.planningcenteronline.com/oauth/applications"
echo ""

ask "PCO App ID" "" PCO_APP_ID
ask_secret "PCO Secret" PCO_SECRET

if [[ -n "$PCO_APP_ID" ]] && [[ -n "$PCO_SECRET" ]]; then
  echo ""
  echo "Testing PCO connection..."
  if python3 "$SCRIPT_DIR/pco_client.py" list-service-types 2>/dev/null | head -5; then
    echo "  PCO connection works."
  else
    echo "  Could not connect. Check your credentials."
  fi
fi

ask "Main worship service type ID (find above, or leave blank to set later)" "" BOOKLET_SERVICE_TYPE_ID

# ── Google Workspace ──────────────────────────────────────────────────
section "Google Workspace (for booklet generation)"
echo "Skip this section if you don't need booklet generation yet."
echo ""

ask "Google service account JSON path (leave blank to skip)" "" GOOGLE_SERVICE_ACCOUNT_FILE
ask "Google OAuth client secret JSON path (leave blank to skip)" "" GOOGLE_OAUTH_CLIENT_SECRET_FILE
ask "Google OAuth token JSON path" "" GOOGLE_OAUTH_TOKEN_FILE
ask "Google Drive template folder ID" "" BOOKLET_GOOGLE_TEMPLATE_ROOT_ID
ask "Google Drive output folder ID" "" BOOKLET_GOOGLE_OUTPUT_ROOT_ID
ask "Ordinary time template doc ID" "" BOOKLET_ORDINARY_TEMPLATE_DOC_ID

# ── APIs ──────────────────────────────────────────────────────────────
section "API Keys"

ask "ESV API token (https://api.esv.org/)" "" ESV_API_TOKEN
ask "Pexels API key (https://www.pexels.com/api/)" "" PEXELS_API_KEY

# ── Booklet Customization ────────────────────────────────────────────
section "Booklet Customization"

ask "Name aliases (e.g. JAM:James,KT:Kim)" "" NAME_ALIASES

# ── Transcription ─────────────────────────────────────────────────────
section "Sermon Transcription"

ask "Subsplash app key (from embed URL, leave blank to skip)" "" SUBSPLASH_APP_KEY
ask "Whisper model" "base" WHISPER_MODEL

# ── Write config.env ──────────────────────────────────────────────────
section "Writing config.env"

cat > "$CONFIG_FILE" << ENVEOF
# Generated by setup.sh — $(date '+%Y-%m-%d %H:%M:%S')

# ── Church Identity ──
CHURCH_NAME=$CHURCH_NAME
CHURCH_LOGO_PATH=$CHURCH_LOGO_PATH

# ── Planning Center ──
PCO_APP_ID=$PCO_APP_ID
PCO_SECRET=$PCO_SECRET

# ── Booklet ──
BOOKLET_SERVICE_TYPE_ID=$BOOKLET_SERVICE_TYPE_ID
BOOKLET_MANIFEST_DB=$SCRIPT_DIR/data/booklet_manifest.sqlite3
BOOKLET_PLANNING_WORKBOOK=$SCRIPT_DIR/data/planning-worksheet.xlsx

# ── Google ──
GOOGLE_SERVICE_ACCOUNT_FILE=$GOOGLE_SERVICE_ACCOUNT_FILE
GOOGLE_OAUTH_CLIENT_SECRET_FILE=$GOOGLE_OAUTH_CLIENT_SECRET_FILE
GOOGLE_OAUTH_TOKEN_FILE=$GOOGLE_OAUTH_TOKEN_FILE
BOOKLET_GOOGLE_TEMPLATE_ROOT_ID=$BOOKLET_GOOGLE_TEMPLATE_ROOT_ID
BOOKLET_GOOGLE_OUTPUT_ROOT_ID=$BOOKLET_GOOGLE_OUTPUT_ROOT_ID
BOOKLET_ORDINARY_TEMPLATE_DOC_ID=$BOOKLET_ORDINARY_TEMPLATE_DOC_ID

# ── APIs ──
ESV_API_TOKEN=$ESV_API_TOKEN
PEXELS_API_KEY=$PEXELS_API_KEY

# ── Booklet Customization ──
NAME_ALIASES=$NAME_ALIASES

# ── Transcription ──
SUBSPLASH_APP_KEY=$SUBSPLASH_APP_KEY
WHISPER_MODEL=$WHISPER_MODEL
ENVEOF

echo "Wrote $CONFIG_FILE"

# ── Initialize data directory ─────────────────────────────────────────
mkdir -p "$SCRIPT_DIR/data"

# Initialize manifest DB if booklet deps are available
if python3 -c "import booklet" 2>/dev/null; then
  python3 "$SCRIPT_DIR/booklet_cli.py" init-manifest 2>/dev/null && echo "Initialized booklet manifest." || true
fi

# ── Install Python dependencies ───────────────────────────────────────
section "Dependencies"
echo "Installing Python dependencies..."
pip3 install -r "$SCRIPT_DIR/requirements.txt" --quiet 2>/dev/null && echo "  Python dependencies installed." || echo "  pip install failed — run manually: pip3 install -r requirements.txt"

# ── Fonts ─────────────────────────────────────────────────────────────
FONT_DIR="$HOME/.local/share/fonts"
if [[ ! -f "$FONT_DIR/PlayfairDisplay.ttf" ]]; then
  echo ""
  echo "Event graphics require Playfair Display and Outfit fonts."
  echo "Download them from Google Fonts and place in $FONT_DIR/:"
  echo "  - PlayfairDisplay.ttf (variable weight)"
  echo "  - PlayfairDisplay-Italic.ttf (variable weight)"
  echo "  - Outfit.ttf (variable weight)"
  echo ""
  echo "Quick install:"
  echo "  mkdir -p $FONT_DIR"
  echo "  # Download from https://fonts.google.com/specimen/Playfair+Display"
  echo "  # Download from https://fonts.google.com/specimen/Outfit"
  echo "  # Place .ttf files in $FONT_DIR/"
else
  echo "  Fonts found at $FONT_DIR/"
fi

# ── Summary ───────────────────────────────────────────────────────────
section "Setup Complete"

echo "Next steps:"
echo ""
[[ -z "$PCO_APP_ID" ]] && echo "  1. Add PCO credentials to config.env"
[[ -z "$GOOGLE_SERVICE_ACCOUNT_FILE" ]] && echo "  2. Set up Google Workspace auth for booklet generation"
[[ -z "$ESV_API_TOKEN" ]] && echo "  3. Get an ESV API token at https://api.esv.org/"
[[ -z "$PEXELS_API_KEY" ]] && echo "  4. Get a Pexels API key at https://www.pexels.com/api/"
echo ""
echo "  Replace logo_white.png with your church's logo."
echo ""
echo "Test your setup:"
echo "  ./pco.sh service-types         # List PCO service types"
echo "  ./pco.sh who-serving            # Who's serving next Sunday"
echo "  python3 generate_event_graphic.py --name 'Test' --date 'Today' --location 'Here' --output /tmp/test.png"
echo ""
echo "For OpenClaw integration, copy skills/ to your OpenClaw workspace."
